### PR TITLE
Adding missing namespace

### PR DESCRIPTION
**Pull request by rafakato**
The client doesn't had a namespace, in my developments I often use namespaces to models like My.Namespace.Playlyfe, and I can't use the SDK because the class name is the same as my namespaces..

### CODE REVIEW

**Comment by pyros2097** [comment]
Huh .. I might have forgotten that since most of the other sdks didn't have namespaces because they were scripting languages ..

**Comment by rafakato** [comment]
Could you please release a new version of the NuGet package?

Thanks

**Comment by pyros2097** [comment]
Ohh Yeah. .Will do!

**Comment by pyros2097** [comment]
Done. Now I remember I had originally done it like this but then you had to type Playlyfe.Playlyfe which looked very awkward.. (needed to do this in the test cases)

**Comment by rafakato** [comment]
It looks weird, but it is needed..

Sorry about the tests..

**Comment by atrniv** [comment]
Consider renaming the class to `Client`. Then you need to type
`Playlyfe.Client`.

**Comment by rafakato** [comment]
It's a way, but when using with the namespace imported like 
```C#
using Playlyfe;
```

the instance will be just `Client playlyfe;`

So it's weird too..

**Pull request merged**
